Repository TeamPiickle/pre-task-client, pull requests merged in 2022-07, with the labels that each got.

#5 [ Ji Yeong- Vote ] 투표기능 구현
  public/mockServiceWorker.js
  src/JiYeong/components/UserProfile/index.tsx
  src/JiYeong/components/UserProfile/style.ts
  src/JiYeong/components/VoteContents/index.tsx
  src/JiYeong/components/VoteContents/style.ts
  src/JiYeong/core/candidate.ts
  src/JiYeong/index.tsx
Labels: Refactor, Fix, 지영, Feature

#7 Test/filter
  src/Filter/index.tsx
  src/Filter/style.ts
  src/Main/index.tsx
  src/Router.tsx
  tsconfig.json
Labels: 주함, Feature

#13 [ Hyeeun - Main ] 필터 기능 구현
  src/HyeEun/filter/components/common/OptionButton/index.tsx
  src/HyeEun/filter/components/common/OptionButton/style.ts
  src/HyeEun/filter/core/optionList.ts
  src/HyeEun/filter/index.tsx
  src/HyeEun/filter/style.ts
  src/HyeEun/filter/util/temp.ts
  src/HyeEun/index.tsx
  src/HyeEun/vote/components/ActionButtons.tsx
  src/HyeEun/vote/components/Header.tsx
  src/HyeEun/vote/components/Survey.tsx
  src/HyeEun/vote/components/common/ActionButton.tsx
  src/HyeEun/vote/components/common/Option.tsx
  src/HyeEun/vote/core/girls.ts
  src/HyeEun/vote/index.tsx
  src/HyeEun/vote/util/temp.ts
  src/Router.tsx
  src/index.tsx
  src/style/index.ts
  src/style/style.d.ts
Labels: 혜은, Feature

#15 [ Nayeon - Main ] progress bar 기능 구현
  src/NaYeon/ImageSlider/components/index.tsx
  src/NaYeon/ImageSlider/components/style.ts
  src/NaYeon/ImageSlider/core/temp.ts
  src/NaYeon/ImageSlider/index.tsx
  src/NaYeon/ImageSlider/util/temp.ts
  src/NaYeon/SliderBar/components/index.tsx
  src/NaYeon/SliderBar/components/style.ts
  src/NaYeon/SliderBar/core/temp.ts
  src/NaYeon/SliderBar/index.tsx
  src/NaYeon/SliderBar/util/temp.ts
  src/NaYeon/components/multiple.tsx
  src/NaYeon/index.tsx
  src/Router.tsx
Labels: 나연, Feature

#19 Feat/#16 swipe
  package.json
  src/Main/index.tsx
  src/Router.tsx
  src/Swipe/SwipeSlider/index.tsx
  src/Swipe/SwipeSlider/styled.ts
  src/Swipe/SwipeSlider/styles.scss
  yarn.lock
Labels: 주함, Feature

#14 [ JiYeong - filter ] 필터기능 구현
  src/JiYeong/filterJY/components/categoryTilte/index.tsx
  src/JiYeong/filterJY/components/categoryTilte/style.ts
  src/JiYeong/filterJY/components/temp.tsx
  src/JiYeong/filterJY/core/filterContents.ts
  src/JiYeong/filterJY/core/resultContents.ts
  src/JiYeong/filterJY/core/temp.ts
  src/JiYeong/filterJY/index.tsx
  src/JiYeong/filterJY/util/temp.ts
  src/JiYeong/index.tsx
  src/JiYeong/voteJY/components/UserProfile/index.tsx
  src/JiYeong/voteJY/components/UserProfile/style.ts
  src/JiYeong/voteJY/components/VoteContents/index.tsx
  src/JiYeong/voteJY/components/VoteContents/style.ts
  src/JiYeong/voteJY/components/temp.tsx
  src/JiYeong/voteJY/core/candidate.ts
  src/JiYeong/voteJY/core/temp.ts
  src/JiYeong/voteJY/index.tsx
  src/JiYeong/voteJY/util/temp.ts
  src/Router.tsx
Labels: 지영, Feature
